[2019-01-09 23:46:10,972] {models.py:1361} INFO - Dependencies all met for <TaskInstance: loans_dag.wait_for_loans 2019-01-02T00:00:00+00:00 [queued]>
[2019-01-09 23:46:10,974] {models.py:1361} INFO - Dependencies all met for <TaskInstance: loans_dag.wait_for_loans 2019-01-02T00:00:00+00:00 [queued]>
[2019-01-09 23:46:10,974] {models.py:1573} INFO - 
--------------------------------------------------------------------------------
Starting attempt 6 of 7
--------------------------------------------------------------------------------

[2019-01-09 23:46:10,980] {models.py:1595} INFO - Executing <Task(PythonSensor): wait_for_loans> on 2019-01-02T00:00:00+00:00
[2019-01-09 23:46:10,981] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run loans_dag wait_for_loans 2019-01-02T00:00:00+00:00 --job_id 72 --raw -sd DAGS_FOLDER/dags/loans_dag.py --cfg_path /var/folders/54/73llq3hj17l3d8lq2zh93p_mmhwfff/T/tmpn1xmq3_9']
[2019-01-09 23:46:11,812] {base_task_runner.py:101} INFO - Job 72: Subtask wait_for_loans [2019-01-09 23:46:11,812] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-01-09 23:46:12,056] {base_task_runner.py:101} INFO - Job 72: Subtask wait_for_loans [2019-01-09 23:46:12,055] {models.py:271} INFO - Filling up the DagBag from /Users/svysyara/PycharmProjects/loans_data/dags/loans_dag.py
[2019-01-09 23:46:12,411] {base_task_runner.py:101} INFO - Job 72: Subtask wait_for_loans [2019-01-09 23:46:12,410] {cli.py:484} INFO - Running <TaskInstance: loans_dag.wait_for_loans 2019-01-02T00:00:00+00:00 [running]> on host 784f43584f2d.ant.amazon.com
[2019-01-09 23:46:12,422] {python_sensor.py:79} INFO - Poking callable: <function check_loans_file_exists at 0x110fe0ea0>
[2019-01-09 23:46:12,422] {logging_mixin.py:95} INFO - [2019-01-09 23:46:12,422] {utils.py:24} INFO - Looking for file: /tmp/loans/2019-01-02/loan.csv
[2019-01-09 23:46:12,422] {base_sensor_operator.py:79} INFO - Success criteria met. Exiting.
[2019-01-09 23:46:15,968] {logging_mixin.py:95} INFO - [2019-01-09 23:46:15,968] {jobs.py:2627} INFO - Task exited with return code 0
